source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ElloOSSUIFonts_Example' do
  pod "ElloOSSUIFonts", :path => "../"
end

target 'ElloOSSUIFonts_Tests' do
  pod "ElloOSSUIFonts", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
