source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ElloOSSUIFonts_Example' do
  pod "ElloOSSUIFonts", :path => "../"
end

target 'ElloOSSUIFonts_Tests' do
  pod "ElloOSSUIFonts", :path => "../"

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.0'
end
