source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ElloOSSUIFonts_Example' do
  pod "ElloOSSUIFonts", :path => "../"
end

target 'ElloOSSUIFonts_Tests' do
  pod "ElloOSSUIFonts", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # cocoapods 1.1.0-rc2 *should* handle this but isn't for some reason
      config.build_settings['SWIFT_VERSION'] = '2.3'
      # cocoapods does not propogate the platform from above
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end